### ISSUE TITLE
Views on the Channel

### ISSUE THREAD

**Issue by linux21123** [Agantor/viewerbot#13]
All good and no Issues but 1 Problem everytime i run that script and the Bots don't stand on that stream much time what is that?! that is bullshit coding sry but it is

**Comment by patsanchique** [comment]
> All good and no Issues but 1 Problem everytime i run that script and the Bots don't stand on that stream much time what is that?! that is bullshit coding sry but it is

please post your configured code, i'm fucking tired of making this work

**Comment by Crazy-Spy** [comment]
Please... send us your code...

**Comment by linux21123** [comment]
why do you want that???
I have write it better as befor my Viewbot is constant of 100 Views

Gesendet: Mittwoch, 05. August 2020 um 23:40 Uhr
Von: "Crazy-Spy" <notifications@github.com>
An: "Agantor/viewerbot" <viewerbot@noreply.github.com>
Cc: "linux21123" <linux-t-pak@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [Agantor/viewerbot] Views on the Channel (#13)


 

Please... send us your code...

**Comment by Crazy-Spy** [comment]
>     why do you want that??? I have write it better as befor my Viewbot is constant of 100 Views Gesendet: Mittwoch, 05. August 2020 um 23:40 Uhr Von: "Crazy-Spy" <notifications@github.com> An: "Agantor/viewerbot" <viewerbot@noreply.github.com> Cc: "linux21123" <linux-t-pak@web.de>, "Author" <author@noreply.github.com> Betreff: Re: [Agantor/viewerbot] Views on the Channel (#13)   Please... send us your code... — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I didn't manage to make it work... :-( do you have any hint? 

is this using the new API already? did you test this recently?

**Comment by Agantor** [comment]
No longer relevant
