### ISSUE TITLE
Can anyone help me?

### ISSUE THREAD

**Issue by Raxana7** [Agantor/viewerbot#22]
![image](https://user-images.githubusercontent.com/48220802/88462153-dd90a980-ceb1-11ea-8a71-fd40c366d24c.png)

**Comment by Crazy-Spy** [comment]
Open the requirements.txt and update the versions numbers with the versions found here https://pypi.org/project/livestreamer/

You will need that for for more than one module.

**Comment by klaudiusmiskinis** [comment]
I just removed all the "==versions" and the error didnt appear anymore. But seems like the proxies can't connect.
