### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by marimendes** [Agantor/viewerbot#24]
File "threads_viewer.py", line 85
    print(f"Sent HEAD request with {current_proxy['http']} | {response.status_code} | {response.request} | {response}")
SyntaxError: invalid syntax

**Comment by PeraDev7** [comment]
how to solve?

**Comment by Agantor** [comment]
Just remove that print...

**Comment by MrJava88** [comment]
File "threads_viewer.py", line 1, in <module>
    import requests
ImportError: No module named requests

**Comment by hhjjj75** [comment]
pip install requests
will fix the problem :)
