### ISSUE TITLE
Unable to get URL

### ISSUE THREAD

**Issue by Motioncapture21** [Agantor/viewerbot#3]
Any working fixes for the Wasnt able to get url error?
Have all the requirements, where does it say "RANDOM CHANNEL".

I have my url put in all the "url" inside the scrip, do I need to put it somewhere else.

**Comment by Rismose** [comment]
For anyone wanting help further on this issue, dm me on discord: Rismose#0079

**Comment by Agantor** [comment]
Duplicate of #34
