### ISSUE TITLE
The specified path was not found.

### ISSUE THREAD

**Issue by Isen267** [Agantor/viewerbot#31]
Hello, 
When I put **"pip install -r requirements.txt"** it's working 
But when I want to write **"~\viewerbot>python threads_viewer.py your_channel_name max_nb_of_threads"** with the good name of the channel with the threads the cmd said **"The specified path was not found."**
Can you help me or It doesn't work anymore

**Comment by zorbeey** [comment]
You dont have to write the „~\viewerbot>“. Its just to clarify to set the path to the viewbot file.
If you dont know how to set the path just use: „cd ./viewerbot“ (or the file name the bot is in). After that write your command **without** the „~\viewerbot>“

I tried my best explaining it as good as possible

**Comment by Agantor** [comment]
@zorbeey explained correctly
