### ISSUE TITLE
No module named 'livestreamer'

### ISSUE THREAD

**Issue by Rafi0li** [Agantor/viewerbot#4]
After I type in "~\viewerbot><b>python threads_viewer.py RANDOMCHANNEL 1000" but with my real details I get this error

Traceback (most recent call last):
  File "threads_viewer.py", line 2, in <module>
    from livestreamer import Livestreamer
ModuleNotFoundError: No module named 'livestreamer'

**Comment by lcsmrlls** [comment]
pip install livestreamer should fix it

**Comment by roxdavirox** [comment]
work?

**Comment by Crazy-Spy** [comment]
I guess it doesn't work anymore.
