### ISSUE TITLE
livestreamer isn't starting

### ISSUE THREAD

**Issue by dukeluke** [Agantor/viewerbot#8]
Hy. 
I tried to get everything correct and installed all modules. script is sending Head requests to a active channel but livestreamer never get startet.

livestreamer is working when i execute livestreamer without script.
I also tried to use streamlink. (changed livestreamer arguments to streamlink),
but I never get any viewers or a livestreamer/streamlink session with the script.
I also read all instructions of the modules, but I cant find any relevant information about this.
Am I missing something?

how I execute:
/usr/bin/python3 /opt/bot/threads_viewer.py channelname 15

python2.7 gives me syntax error:

`File "/opt/bot/threads_viewer.py", line 85
    print(f"Sent HEAD request with {current_proxy['http']} | {response.status_code} | {response.request} | {response}")
                                                                                                                     ^
SyntaxError: invalid syntax
`

**Comment by kalodis** [comment]
Duke. Please read the other issues: i posted a fix to this.


I quote RIGHT FROM THE CODE:

`if name == "main":

if len(sys.argv) == 1:
    channel_url = "https://www.twitch.tv/" + sys.argv[1]
else:
    channel_url = "https://www.twitch.tv/your_channel_name"
start_time = time.time()
proxies = get_proxies()
`

Where you see "channel_url="https://www.twitch.tv/your_channel_name"

Change your_channel_name to YOUR CHANNEL NAME

Save the code.

Run the code as follows. (Make sure you have a good proxy list and know how to map that within the code please)

Change directories to the directory where you have the code stored.

Example:

cd /home/user/viewbot

Then run the code below
'python threads_viewer.py YOURCHANNELNAME 1000'

Also. Make sure you are running python 3.7 or higher. Good luck.

**Comment by dukeluke** [comment]
> 
> 
> Duke. Please read the other issues: i posted a fix to this.
> 
> I quote RIGHT FROM THE CODE:
> 
> `if name == "main":
> 
> if len(sys.argv) == 1:
> channel_url = "https://www.twitch.tv/" + sys.argv[1]
> else:
> channel_url = "https://www.twitch.tv/your_channel_name"
> start_time = time.time()
> proxies = get_proxies()
> `
> 
> Where you see "channel_url="https://www.twitch.tv/your_channel_name"
> 
> Change your_channel_name to YOUR CHANNEL NAME
> 
> Save the code.
> 
> Run the code as follows. (Make sure you have a good proxy list and know how to map that within the code please)
> 
> Change directories to the directory where you have the code stored.
> 
> Example:
> 
> cd /home/user/viewbot
> 
> Then run the code below
> 'python threads_viewer.py YOURCHANNELNAME 1000'
> 
> Also. Make sure you are running python 3.7 or higher. Good luck.

**Comment by dukeluke** [comment]
Read the other issues already 500 times.
changed my script to /home/user directory.--> same problem
channel_url = "https://www.twitch.tv/your_channel_name" was always definded.

python isn't starting this script. Error in post 1.
python3 or python3.7 does, but script spams ****connection error***** and Wasn't able to get url.

Also tried to use original good_proxy.txt file and a proxylist from https://www.proxy-listen.de. and yes the are mapped same like the good_proxy.txt file.
Also tried to execute scipt this way: python3.7 threads_viewer.py YOURCHANNELNAME 1000 
but it never worked.
I use ubuntu 18.04 & python3.7
Installed all modules for python3.7. No Luck
