### ISSUE TITLE
Wasnt able to get url

### ISSUE THREAD

**Issue by eroslico** [Agantor/viewerbot#9]
Set the entire bot correctly as remembered, since at the time I managed to make it work but this time it just constantly tells me "Wasnt able to get url" ..

Has anyone managed to make it work?
Twitch changed something that causes the bot not to work?

thanks

**Comment by Shazgul** [comment]
Also getting this Error, maybe sum1 got an Fix?

**Comment by brunomaffei** [comment]
I'm getting this error too if someone could help

**Comment by Rismose** [comment]
same issue

**Comment by Rismose** [comment]
For anyone wanting help further on this issue, dm me on discord: Rismose#0079

**Comment by klaudiusmiskinis** [comment]
If you someone fixed it, im interested; discord: Itacho#2624

**Comment by Agantor** [comment]
[iLoooordFx](https://github.com/iLoooordFx) made an update. Should work now (I haven't tested). Thanks
